---
# tasks file for mariadb

- name: Include distribution specific variables
  include_vars: "{{ ansible_distribution }}.yml"
  tags: mariadb

- include: CentOS.yml
  when: ansible_distribution == "CentOS"
  tags: mariadb

- include: Ubuntu.yml
  when: ansible_distribution == "Ubuntu"
  tags: mariadb

- name: Create MariaDB main configuration file
  template: >
    src=my.cnf.j2
    dest=/etc/mysql/my.cnf
    owner=root
    group=root
    mode=0644
  notify: restart mariadb
  when: mariadb_server
  tags:
    - mariadb
    - mariadb_server

- name: Create MariaDB specific configuration file
  template: >
    src=mariadb.cnf.j2
    dest=/etc/mysql/conf.d/mariadb.cnf
    owner=root
    group=root
    mode=0644
  notify: restart mariadb
  when: mariadb_server
  tags:
    - mariadb
    - mariadb_server

- name: Create MariaDB safe syslog configuration file
  template: >
    src=mysqld_safe_syslog.cnf.j2
    dest=/etc/mysql/conf.d/mysqld_safe_syslog.cnf
    owner=root
    group=root
    mode=0644
  notify: restart mariadb
  when: mariadb_server
  tags:
    - mariadb
    - mariadb_server

- name: Create MariaDB TokuDB configuration file
  template: >
    src=tokudb.cnf.j2
    dest=/etc/mysql/conf.d/tokudb.cnf
    owner=root
    group=root
    mode=0644
  notify: restart mariadb
  when: mariadb_server
  tags:
    - mariadb
    - mariadb_server

- name: Ensure MariaDB server is started and enabled on boot
  service: name={{ mariadb_service_name }} state=started enabled=yes
  when: mariadb_server
  tags:
    - mariadb
    - mariadb_server
